### ISSUE TITLE
script compile error

### ISSUE THREAD

**Issue by K-Faktor** [livingston/cod4-novo#1]
******* script compile error *******
Error: Could not find script 'openwarfare/_utils': (file 'maps/mp/gametypes/_globallogic.gsx', line 17)
#include openwarfare\_utils;
*
************************************
----- Server Shutdown -----

**Comment by livingston** [comment]
The current script runs along with openwarfare, that is why you are getting this error.

**Comment by K-Faktor** [comment]
Good thank you
